export const ADD_POKEMONS = 'ADD_POKEMONS';
export const POKEMONS_LOADING = 'POKEMONS_LOADING';
export const POKEMONS_FAILED = 'POKEMONS_FAILED';
export const POKEMON_LIKED = 'POKEMON_LIKED';
export const POKEMON_DISLIKED = 'POKEMON_DISLIKED';